server:
  port: 9527

spring:
  application:
    name: springcloud-eureka-zuul-gateway

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-eureka-zuul-gateway-9527
    prefer-ip-address: true

#
zuul:
  #ignored-services: microservicecloud-dept
  prefix: /snym
  ignored-services: "*"
  routes:
    mydept.serviceId: springcloud-eureka-dept
    mydept.path: /mydept/**


info:
  app.name: springcloud
  company.name: www.snym.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
